SetAttackBaseDamage(24, 30)
SetAttackMaxPP(24, 30)
SetAttackCategory(24, Attacks_GetCategoryIndexByName("physical"))
SetAttackContestCategory(24, Attacks_GetContestCategoryIndexByName("cool"))
SetAttackAttackCategory(24, Attacks_GetAttackCategoryIndexByName("damage"))
SetAttackType(24, Attacks_GetTypeIndexByName("fighting"))
SetAttackPriority(24, 0)
SetAttackAccuracy(24,255)
SetAttackTimesToAttack(24,2)