SetAttackBaseDamage(2, 50)
SetAttackMaxPP(2, 25)
SetAttackCategory(2, Attacks_GetCategoryIndexByName("physical"))
SetAttackContestCategory(2, Attacks_GetContestCategoryIndexByName("tough"))
SetAttackAttackCategory(2, Attacks_GetAttackCategoryIndexByName("damage"))
SetAttackType(2, Attacks_GetTypeIndexByName("fighting"))
SetAttackPriority(2, 0)
SetAttackAccuracy(2,255)
SetAttackHighCriticalChance(2, true)