SetAttackBaseDamage(136, 130)
SetAttackMaxPP(136, 10)
SetAttackCategory(136, Attacks_GetCategoryIndexByName("physical"))
SetAttackContestCategory(136, Attacks_GetContestCategoryIndexByName("cool"))
SetAttackAttackCategory(136, Attacks_GetAttackCategoryIndexByName("damage"))
SetAttackType(136, Attacks_GetTypeIndexByName("fighting"))
SetAttackPriority(136, 0)
SetAttackAccuracy(136,229)
SetAttackMissedDelegate(136, "ATTACKS_FIGHTING_HI_JUMP_KICK_MISSED")

function ATTACKS_FIGHTING_HI_JUMP_KICK_MISSED()
    local recoil = math.floor(Attacks_MyHP / 2)
    Attacks_AddBattleStep("DrainHP", Attacks_TargetString .. "|" .. tostring(recoil))
    Attacks_AddBattleStep("Message", Attacks_MyName .. " is damaged~by recoil!")
end