SetAttackBaseDamage(560,75)
SetAttackMaxPP(560, 15)
SetAttackCategory(560, Attacks_GetCategoryIndexByName("physical"))
SetAttackContestCategory(560, Attacks_GetContestCategoryIndexByName("tough"))
SetAttackAttackCategory(560, Attacks_GetAttackCategoryIndexByName("damage"))
SetAttackType(560, Attacks_GetTypeIndexByName("fighting"))
SetAttackPriority(560, 0)
SetAttackAccuracy(560,229)