SetAttackBaseDamage(114,0)
SetAttackMaxPP(114,30)
SetAttackCategory(114,2)
SetAttackContestCategory(114,2)
SetAttackType(114,14)
SetAttackPriority(114,0)
SetAttackAccuracy(114,-1)
SetAttackSpecialAttackDelegate(114, "ATTACKS_ICE_HAZE_SPECIAL")

function ATTACKS_ICE_HAZE_SPECIAL()
    local T = Attacks_TargetString
    Attacks_AddBattleStep("ResetStat", T .. "|Attack|0")
    Attacks_AddBattleStep("ResetStat", T .. "|Defense|0")
    Attacks_AddBattleStep("ResetStat", T .. "|SpAttack|0")
    Attacks_AddBattleStep("ResetStat", T .. "|SpDefense|0")
    Attacks_AddBattleStep("ResetStat", T .. "|Speed|0")
    Attacks_AddBattleStep("ResetStat", T .. "|Accuracy|0")
    Attacks_AddBattleStep("ResetStat", T .. "|Evasion|0")
    T = Attacks_GetTargetStringByAttackTarget("user")
    Attacks_AddBattleStep("ResetStat", T .. "|Attack|0")
    Attacks_AddBattleStep("ResetStat", T .. "|Defense|0")
    Attacks_AddBattleStep("ResetStat", T .. "|SpAttack|0")
    Attacks_AddBattleStep("ResetStat", T .. "|SpDefense|0")
    Attacks_AddBattleStep("ResetStat", T .. "|Speed|0")
    Attacks_AddBattleStep("ResetStat", T .. "|Accuracy|0")
    Attacks_AddBattleStep("ResetStat", T .. "|Evasion|0")
    Attacks_AddBattleStep("Message", "All stat changes were~eliminated!")
end